import { inter } from "./Fonts/fonts";
import "./globals.css";

export const metadata = {
  title: "Security And System",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
